//file:noinspection VulnerableLibrariesLocal
plugins {
    id 'java'
}

version 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':api')
    implementation project(':versions-adapter-1_8-1_12_2')
    implementation project(':versions-adapter-1_13-1_20_4')

    compileOnly 'io.papermc.paper:paper-api:26.2.build.+'
}
