//file:noinspection VulnerableLibrariesLocal
plugins {
    id 'java'
}

version 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    shade project(':api')
    shade project(':text-adventure')
    shade project(':text-bungee')
    shade project(':versions-adapter-1_8-1_12_2')
    shade project(':versions-adapter-1_13-1_20_4')
    shade project(':versions-adapter-1_20_5-and-more')

    compileOnly 'io.papermc.paper:paper-api:26.2.build.+'
}

jar {
    destinationDirectory = file('..\\build')
    archiveFileName.set("PhysicsControl-26.2.jar")
}
