name: PhysicsControl
version: "1.4.1"
main: ru.dymeth.pcontrol.PhysicsControl
description: 'Paper 26.2 world physics controller plugin'
api-version: "26.2"
softdepend: [MultiWorld, MultiVerse]
commands:
    physicscontrol:
        description: 'Basic PhysicsControl plugin command'
        aliases: ["pcontrol", "physicsc", "pc"]
author: Dymeth
folia-supported: true
